name: byewall3
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 
  dynamic_color: ^1.7.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  path: ^1.9.1
  diacritic: ^0.1.6
  path_provider: ^2.1.5
  flutter_slidable: ^4.0.0
  window_manager: ^0.4.3
  hive_ce: ^2.11.1
  hive_ce_flutter: ^2.3.0
  floating_navbar: ^3.0.0
  flutter_custom_tabs: ^2.4.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.1
  build_runner: ^2.4.7

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
  - lang/en_US.json
  - lang/es_ES.json
  - lang/pt_BR.json
  - lang/pl.json
